### ISSUE TITLE
sdmmc.c is licensed as GPLv2+, yet the code using it is licensed under a different license.

### ISSUE THREAD

**Issue by neobrain** [delebile/arm9loaderhax#1]
This project is using code licensed under the GPLv2, which requires the whole project (!) needs to be licensed as that, too.

I'm sure this is just an oversight and can be fixed easily by exchanging the license of this project. If it's not an oversight, please don't use GPL-licensed code if you aren't willing to conform to the license in the first place - please understand that many people wouldn't be releasing source code at all if it wasn't for the benefits guaranteed in the GPL.

**Comment by jasondellaluce** [comment]
You are right, i actually deleted my license file in the last commit (which i just copy-pasted without thinking too much on it, my bad) and added proper credits in the readme.
I'll consider to use GPLv2, but i'll first read better the terms.
If it's a problem i can actually not license as mine the code written here, i actually do not mind too much.

**Comment by neobrain** [comment]
There is no need to read better the terms; it's really simple, since you have two options:
- If you want to use another license than GPLv2 or GPLv3, get rid of the code and write the functionality yourself from scratch
- Otherwise, just license the whole arm9loaderhax code as GPLv2 or GPLv3. This is the preferred option, since it requires virtually no extra effort on your side, yet preserves all the rights that end users have.

There are plenty of places to read about this on the Internet, in particular from the Free Software Foundation, who are essentially the creators of the GPL: https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic for instances sums up all of what I just said in three very brief paragraphs, in particular:

> But if you release the modified version to the public in some way, the GPL requires you to make the modified source code available to the program's users, under the GPL.

**Comment by jasondellaluce** [comment]
It should be ok now i guess.

**Comment by neobrain** [comment]
Looks fine, thanks!

**Comment by jasondellaluce** [comment]
Thanks to you for pointing it out! ^^
