### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by urherenow** [delebile/arm9loaderhax#10]
"The problem here is that it doesn't still initialize the screens, that has still to be achieved, though i was able to load an external patched firmware and make boot the console without any problem while testing."

This is no longer true. But... do we install the whole thing again (is it safe to do so)? Or will there be an updater added?

**Comment by sykhro** [comment]
There is an updater, but afaik it doesn't always work on n3ds [download](https://gbatemp.net/attachments/installer-zip.40329/)

**Comment by pixel-stuck** [comment]
the updater works sometimes on n3ds, sometimes the baked in screen init doesn't work on n3ds, but the rest does and sometimes it just flat out doesn't work on n3ds :/

o3ds is 100% though afaik

**Comment by mariogamer2** [comment]
https://github.com/delebile/arm9loaderhax/pull/12

**Comment by urherenow** [comment]
Actually, I used the updater on both my o3ds and n3ds. Both worked perfectly the first time, and both boot 100% of the time.

**Comment by pixel-stuck** [comment]
@urherenow it's console dependant... on the consoles it works on it works 100% of the time, but some consoles refuse to boot it, others just don't have proper screen init
