### ISSUE TITLE
[SUGGESTION] Implement security checks in Installer

### ISSUE THREAD

**Issue by mlinares1998** [delebile/arm9loaderhax#16]
I suggest adding some type of checks on 3dsx installer before install FIRM0/1, a dude who I talk bricked his 3DS for putting OTP in wrong folder, installer succeded with FIRM0/1 install, Then rebooted console and showed BROM error...
In some forums people reported succesful compile but at install they bricked their 3DS too.

**Comment by mariogamer2** [comment]
Yeah it will be good...

**Comment by tsubasamanda** [comment]
What do you mean by "in the wrong folder"?

**Comment by urherenow** [comment]
Obviously, the dude didn't put the OTP.bin into the data_input folder, but since there happened to be an OTP.bin in there already (whether it was 0 byte or just someone else's) , a9lh happily compiled... You do the math

At the moment though, I don't see a fork setup that way. Maybe that person got the source outside of github or something. With no OTP.bin at all in the correct folder, it shouldn't compile...

**Comment by tsubasamanda** [comment]
Oh, alright. You could probably check at compile time.

**Comment by urherenow** [comment]
Check what? The only thing to check is whether or not it is a 0 byte file. Impossible to check if it's "the correct one".

**Comment by tsubasamanda** [comment]
I know. The best way would be to modify the section generator to check if the OTP.bin is 256 bytes long.

**Comment by mariogamer2** [comment]
@TechNick6425 Probably very simple,shearching on google.... XD

**Comment by mariogamer2** [comment]
personally,I don't view what is these "check",it is pretty impossible to define if the installer is good of the 3DS who are using it...
#19

**Comment by mlinares1998** [comment]
Sorry for really late response... XD

@mariogamer2 

> personally,I don't view what is these "check",it is pretty impossible to define if the installer is good of the 3DS who are using it...

Your commit catch the idea, it will prevent A9LH compile with bad OTP, my suggestion was do that at installer side if was possible if Installer has unvalid OTP will refuse to install of course not per console check, thats unpossible X"D.

By checks i thought also on automatic backup of FIRM partitions, if something goes wrong installer restore ATM FIRM partitions to original state, excellent if exist a way to check A9LH is installed correctly, That should make the installer more Failsafe.

Sorry if the ideas are bad explained XD I'm dont really good with words.

**Comment by mariogamer2** [comment]
The 2nd idea is good.

**Comment by mariogamer2** [comment]
Hey: https://github.com/AuroraWright/SafeA9LHInstaller

It is possible!!!!

**Comment by mlinares1998** [comment]
@mariogamer2

> Hey: https://github.com/AuroraWright/SafeA9LHInstaller
> 
> It is possible!!!!

SafeA9LHInstaller is truly awesome, @AuroraWright is a master XD. 
Maybe we can open a suggestion issue proposing FIRM partitions auto bak/restore, by me the only thing it lacks XD.
So we can consider this issue closed now?

**Comment by mariogamer2** [comment]
Not totally...

**Comment by mlinares1998** [comment]
OK i'll leave it opened...

**Comment by urherenow** [comment]
Holy crap! I stand corrected :)

**Comment by mariogamer2** [comment]
Humm,don't know if it is more related to https://github.com/delebile/arm9loaderhax/issues/18 .

**Comment by jasondellaluce** [comment]
Many sanity checks are done in the new update, this should now be satisfed.
