### ISSUE TITLE
Typo in readme's setup 

### ISSUE THREAD

**Issue by capito27** [delebile/arm9loaderhax#2]
in this place : "new3ds10.firm : New 3DS NATIVE_FIRM from system version 10.0. You can dump and decrypt it from both the CDN, NAND, the proper 0004013800000002.cia, or in any way get it leaked."

it is actually the native_firm from 10.2 and the cia name is 00040138**2**0000002.cia, according to the provided hash and [This post](https://gbatemp.net/threads/aes-key-scrambler.406951/page-23#post-6016003)

**Comment by jasondellaluce** [comment]
Thanks for pointing out the error.
