### ISSUE TITLE
[Suggestion] Link to SafeA9LHInstaller in readme

### ISSUE THREAD

**Issue by DessertArbiter** [delebile/arm9loaderhax#20]
New safer updater/installer by Aurora Wright: [SafeA9LHInstaller](http://gbatemp.net/threads/safea9lhinstaller.419577/) ([Github link](https://github.com/AuroraWright/SafeA9LHInstaller/releases))

**Comment by jasondellaluce** [comment]
The new update performs many integrity checks at different levels with hashes, so it is now really safe.
