### ISSUE TITLE
Compiler warnings while making arm9loaderhax.pack (Varius)

### ISSUE THREAD

**Issue by urherenow** [delebile/arm9loaderhax#25]
Was going to post some, but there are too many. Some are silly, like missing semicolons, but others make me question how safe this is to use. There are not only conflicting argument types, but incompatible ones as well... One example:

x:/devkitPro/devkitARM/projects/arm9loaderhax/payload_stage2/source/main.c:67:51: warning: passing argument 4 of 'f_read' from incompatible pointer type [-Wincompatible-pointer-types]
   f_read(&payload, PAYLOAD_ADDRESS, PAYLOAD_SIZE, &br);

**Comment by jasondellaluce** [comment]
I'll try to clean them up, but they should not give any real problem.

**Comment by jasondellaluce** [comment]
I just pulled a fix for this, [look here](https://github.com/delebile/arm9loaderhax/commit/807d7bffec566fc4c039d6c909e9a1a2e81ddbc2), now it doesn't show any warning.
